# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interfaz.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1097, 692)
        MainWindow.setMinimumSize(QSize(1097, 692))
        MainWindow.setMaximumSize(QSize(1097, 692))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 20, 1061, 661))
        self.tabWidget.setStyleSheet(u"")
        self.Carreras = QWidget()
        self.Carreras.setObjectName(u"Carreras")
        self.label = QLabel(self.Carreras)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 121, 21))
        self.label_2 = QLabel(self.Carreras)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 130, 131, 21))
        self.claveCarrera = QLineEdit(self.Carreras)
        self.claveCarrera.setObjectName(u"claveCarrera")
        self.claveCarrera.setGeometry(QRect(160, 90, 201, 31))
        self.claveCarrera.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.nombreCarrera = QLineEdit(self.Carreras)
        self.nombreCarrera.setObjectName(u"nombreCarrera")
        self.nombreCarrera.setGeometry(QRect(160, 130, 351, 31))
        self.nombreCarrera.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.tableWidget = QTableWidget(self.Carreras)
        if (self.tableWidget.columnCount() < 2):
            self.tableWidget.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(15, 271, 1021, 341))
        self.tableWidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.btn_registrar = QPushButton(self.Carreras)
        self.btn_registrar.setObjectName(u"btn_registrar")
        self.btn_registrar.setGeometry(QRect(890, 210, 121, 41))
        self.mensaje = QLabel(self.Carreras)
        self.mensaje.setObjectName(u"mensaje")
        self.mensaje.setGeometry(QRect(40, 200, 431, 31))
        self.tabWidget.addTab(self.Carreras, "")
        self.Alumnos = QWidget()
        self.Alumnos.setObjectName(u"Alumnos")
        self.label_3 = QLabel(self.Alumnos)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 60, 191, 21))
        self.label_4 = QLabel(self.Alumnos)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 110, 131, 21))
        self.label_5 = QLabel(self.Alumnos)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 160, 91, 21))
        self.label_6 = QLabel(self.Alumnos)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 210, 91, 21))
        self.A_noControl = QLineEdit(self.Alumnos)
        self.A_noControl.setObjectName(u"A_noControl")
        self.A_noControl.setGeometry(QRect(240, 60, 191, 31))
        self.A_nombreAlumno = QLineEdit(self.Alumnos)
        self.A_nombreAlumno.setObjectName(u"A_nombreAlumno")
        self.A_nombreAlumno.setGeometry(QRect(180, 110, 191, 31))
        self.A_genero = QComboBox(self.Alumnos)
        self.A_genero.addItem("")
        self.A_genero.addItem("")
        self.A_genero.addItem("")
        self.A_genero.addItem("")
        self.A_genero.setObjectName(u"A_genero")
        self.A_genero.setGeometry(QRect(140, 160, 191, 31))
        self.A_carrera = QComboBox(self.Alumnos)
        self.A_carrera.addItem("")
        self.A_carrera.setObjectName(u"A_carrera")
        self.A_carrera.setGeometry(QRect(140, 210, 191, 31))
        self.A_tabla = QTableWidget(self.Alumnos)
        if (self.A_tabla.columnCount() < 4):
            self.A_tabla.setColumnCount(4)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.A_tabla.setHorizontalHeaderItem(0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.A_tabla.setHorizontalHeaderItem(1, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.A_tabla.setHorizontalHeaderItem(2, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.A_tabla.setHorizontalHeaderItem(3, __qtablewidgetitem5)
        self.A_tabla.setObjectName(u"A_tabla")
        self.A_tabla.setGeometry(QRect(20, 270, 1021, 341))
        self.A_tabla.horizontalHeader().setCascadingSectionResizes(False)
        self.A_tabla.horizontalHeader().setDefaultSectionSize(250)
        self.A_tabla.horizontalHeader().setHighlightSections(True)
        self.A_tabla.horizontalHeader().setProperty("showSortIndicator", False)
        self.A_tabla.horizontalHeader().setStretchLastSection(True)
        self.A_btnRegistrar = QPushButton(self.Alumnos)
        self.A_btnRegistrar.setObjectName(u"A_btnRegistrar")
        self.A_btnRegistrar.setGeometry(QRect(900, 210, 121, 41))
        self.A_mensaje = QLabel(self.Alumnos)
        self.A_mensaje.setObjectName(u"A_mensaje")
        self.A_mensaje.setGeometry(QRect(440, 70, 451, 16))
        self.tabWidget.addTab(self.Alumnos, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 1011, 271))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 30, 121, 31))
        self.C_numero_Control = QLineEdit(self.groupBox)
        self.C_numero_Control.setObjectName(u"C_numero_Control")
        self.C_numero_Control.setGeometry(QRect(150, 30, 211, 31))
        self.C_btnBuscar_Control = QPushButton(self.groupBox)
        self.C_btnBuscar_Control.setObjectName(u"C_btnBuscar_Control")
        self.C_btnBuscar_Control.setGeometry(QRect(370, 30, 93, 28))
        self.C_tabla_Control = QTableWidget(self.groupBox)
        if (self.C_tabla_Control.columnCount() < 4):
            self.C_tabla_Control.setColumnCount(4)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.C_tabla_Control.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.C_tabla_Control.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.C_tabla_Control.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.C_tabla_Control.setHorizontalHeaderItem(3, __qtablewidgetitem9)
        self.C_tabla_Control.setObjectName(u"C_tabla_Control")
        self.C_tabla_Control.setGeometry(QRect(10, 80, 991, 181))
        self.C_tabla_Control.horizontalHeader().setCascadingSectionResizes(False)
        self.C_tabla_Control.horizontalHeader().setDefaultSectionSize(200)
        self.C_tabla_Control.horizontalHeader().setHighlightSections(True)
        self.C_tabla_Control.horizontalHeader().setProperty("showSortIndicator", False)
        self.C_tabla_Control.horizontalHeader().setStretchLastSection(True)
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 290, 1011, 321))
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 30, 61, 31))
        self.C_carrera_Carrera = QComboBox(self.groupBox_2)
        self.C_carrera_Carrera.setObjectName(u"C_carrera_Carrera")
        self.C_carrera_Carrera.setGeometry(QRect(110, 30, 231, 31))
        self.C_btnBuscar_Carrera = QPushButton(self.groupBox_2)
        self.C_btnBuscar_Carrera.setObjectName(u"C_btnBuscar_Carrera")
        self.C_btnBuscar_Carrera.setGeometry(QRect(350, 30, 93, 28))
        self.C_tabla_Carrera = QTableWidget(self.groupBox_2)
        if (self.C_tabla_Carrera.columnCount() < 4):
            self.C_tabla_Carrera.setColumnCount(4)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.C_tabla_Carrera.setHorizontalHeaderItem(0, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.C_tabla_Carrera.setHorizontalHeaderItem(1, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.C_tabla_Carrera.setHorizontalHeaderItem(2, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.C_tabla_Carrera.setHorizontalHeaderItem(3, __qtablewidgetitem13)
        self.C_tabla_Carrera.setObjectName(u"C_tabla_Carrera")
        self.C_tabla_Carrera.setGeometry(QRect(10, 80, 991, 231))
        self.C_tabla_Carrera.horizontalHeader().setCascadingSectionResizes(False)
        self.C_tabla_Carrera.horizontalHeader().setDefaultSectionSize(200)
        self.C_tabla_Carrera.horizontalHeader().setHighlightSections(True)
        self.C_tabla_Carrera.horizontalHeader().setProperty("showSortIndicator", False)
        self.C_tabla_Carrera.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        self.tabWidget.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Clave de la carrera: ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Nombre de la carrera:", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Clave de la carrera", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Nombre de la carrera", None));
        self.btn_registrar.setText(QCoreApplication.translate("MainWindow", u"Registrar", None))
        self.mensaje.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Carreras), QCoreApplication.translate("MainWindow", u"Carreras", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Numero de control del alumno: ", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Nombre del alumno: ", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Genero:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Carerra:", None))
        self.A_genero.setItemText(0, QCoreApplication.translate("MainWindow", u"--- Seleccione ---", None))
        self.A_genero.setItemText(1, QCoreApplication.translate("MainWindow", u"Masculino", None))
        self.A_genero.setItemText(2, QCoreApplication.translate("MainWindow", u"Femenino", None))
        self.A_genero.setItemText(3, QCoreApplication.translate("MainWindow", u"Sin especificar", None))

        self.A_carrera.setItemText(0, QCoreApplication.translate("MainWindow", u"--- Seleccione ---", None))

        self.A_carrera.setCurrentText(QCoreApplication.translate("MainWindow", u"--- Seleccione ---", None))
        ___qtablewidgetitem2 = self.A_tabla.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"No. de control", None));
        ___qtablewidgetitem3 = self.A_tabla.horizontalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Alumno", None));
        ___qtablewidgetitem4 = self.A_tabla.horizontalHeaderItem(2)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Genero", None));
        ___qtablewidgetitem5 = self.A_tabla.horizontalHeaderItem(3)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Carrera", None));
        self.A_btnRegistrar.setText(QCoreApplication.translate("MainWindow", u"Registrar", None))
        self.A_mensaje.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Alumnos), QCoreApplication.translate("MainWindow", u"Alumnos", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Consultar alumnos", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"N\u00famero de control: ", None))
        self.C_btnBuscar_Control.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        ___qtablewidgetitem6 = self.C_tabla_Control.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"No. de control", None));
        ___qtablewidgetitem7 = self.C_tabla_Control.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Alumno", None));
        ___qtablewidgetitem8 = self.C_tabla_Control.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Genero", None));
        ___qtablewidgetitem9 = self.C_tabla_Control.horizontalHeaderItem(3)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Carrera", None));
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Listar alumnos por carrera", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Carrera:", None))
        self.C_btnBuscar_Carrera.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        ___qtablewidgetitem10 = self.C_tabla_Carrera.horizontalHeaderItem(0)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"No. de control", None));
        ___qtablewidgetitem11 = self.C_tabla_Carrera.horizontalHeaderItem(1)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Alumno", None));
        ___qtablewidgetitem12 = self.C_tabla_Carrera.horizontalHeaderItem(2)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Genero", None));
        ___qtablewidgetitem13 = self.C_tabla_Carrera.horizontalHeaderItem(3)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Carrera", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Consultar", None))
    # retranslateUi

