# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1095, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1071, 661))
        self.tabWidget.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.tabWidget.setObjectName("tabWidget")
        self.Carreras = QtWidgets.QWidget()
        self.Carreras.setObjectName("Carreras")
        self.label = QtWidgets.QLabel(self.Carreras)
        self.label.setGeometry(QtCore.QRect(20, 90, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Carreras)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 131, 21))
        self.label_2.setObjectName("label_2")
        self.claveCarrera = QtWidgets.QLineEdit(self.Carreras)
        self.claveCarrera.setGeometry(QtCore.QRect(160, 90, 201, 31))
        self.claveCarrera.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.claveCarrera.setObjectName("claveCarrera")
        self.nombreCarrera = QtWidgets.QLineEdit(self.Carreras)
        self.nombreCarrera.setGeometry(QtCore.QRect(160, 130, 351, 31))
        self.nombreCarrera.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.nombreCarrera.setObjectName("nombreCarrera")
        self.btn_Registrar = QtWidgets.QPushButton(self.Carreras)
        self.btn_Registrar.setGeometry(QtCore.QRect(890, 220, 93, 28))
        self.btn_Registrar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_Registrar.setObjectName("btn_Registrar")
        self.tableWidget = QtWidgets.QTableWidget(self.Carreras)
        self.tableWidget.setGeometry(QtCore.QRect(15, 291, 1041, 331))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.Carreras, "")
        self.Alumnos = QtWidgets.QWidget()
        self.Alumnos.setObjectName("Alumnos")
        self.tabWidget.addTab(self.Alumnos, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Clave de la carrera: "))
        self.label_2.setText(_translate("MainWindow", "Nombre de la carrera:"))
        self.btn_Registrar.setText(_translate("MainWindow", "Registrar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Clave de la carrera"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre de la carrera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Carreras), _translate("MainWindow", "Carreras"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Alumnos), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
